kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: latest-amd64
      build_args_from_env:
        - DRONE_STAGE_ARCH
      repo: imemjay/resticker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: plugins/docker:linux-arm
    settings:
      tags: latest-arm
      build_args_from_env:
        - DRONE_STAGE_ARCH
      repo: imemjay/resticker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/docker:linux-arm64
    settings:
      tags: latest-arm64
      build_args_from_env:
        - DRONE_STAGE_ARCH
      repo: imemjay/resticker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
---
kind: pipeline
name: manifest

steps:
  - name: manifest
    image: plugins/manifest:1
    settings:
      spec: manifest.tmpl
      use_default_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64

depends_on:
  - amd64
  - arm
  - arm64
